### PR TITLE
drop python3.6 support

### PR DESCRIPTION
**Pull request by asottile**
python 3.6 reached end of life on 2021-12-23

Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by pelson** [comment]
Py3.6 is dead :tada:

That said, if you happen to have something ``<=3.6`` lying around (as I did from some time ago) and you use ``pre-commit``, ``pip`` really doesn't handle the incompatibility very well:

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/add-trailing-comma.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/pelson/.cache/pre-commit/repolko2zs1a/py_env-python3.6/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/pelson/.cache/pre-commit/repolko2zs1a
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/pelson/.cache/pre-commit/repolko2zs1a/py_env-python3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pelson/.cache/pre-commit/repolko2zs1a/setup.py'"'"'; __file__='"'"'/home/pelson/.cache/pre-commit/repolko2zs1a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-whn9zf9f
           cwd: /home/pelson/.cache/pre-commit/repolko2zs1a/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/pelson/.cache/pre-commit/repolko2zs1a/setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
    WARNING: Discarding file:///home/pelson/.cache/pre-commit/repolko2zs1a. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    
Check the log at /home/pelson/.cache/pre-commit/pre-commit.log
```

The easy fix for me is to use a newer Python :stuck_out_tongue_winking_eye:. That said, there is no need for the incompatible future definition in the ``setup.py`` (since it is just a shim to read the ``setup.cfg``). If that were done, a more helpful error would have been shown (pip telling me that py36 isn't supported). 

By the same token, I'm not sure if it would have been better for pre-commit to pick up the wheel from PyPI.org instead of building from source. Is this something that ``pre-commit`` can already do? (workarounds discussed in https://github.com/pre-commit/pre-commit/issues/1705#issuecomment-731279327, something that I would be prepared to contribute if there was a clear direction)

**Comment by pelson** [comment]
> nope, pre-commit should build from source and this is exactly as intended

That is fair, though it was my addendum, not the main point.

My main point being: The ``setup.py`` is not valid Python <3.6 syntax. It means that as it stands, there isn't much point in the [``python>=3.7`` specification in ``setup.cfg``](https://github.com/asottile/add-trailing-comma/blob/13b40b413fe66c0bea045934a1f37e494d809b92/setup.cfg) (other than it is nice and explicit). If the ``setup.py`` were valid syntax (which it can easily be, since it is just a proxy ``setup.py``), then the error would be more along the lines of:

```
$ pip install .
Processing /tmp/add-trailing-comma
Requirement already satisfied: tokenize-rt>=3.0.1 in ./env-delme/lib/python3.6/site-packages/tokenize_rt-4.2.1-py3.6.egg (from add-trailing-comma==2.2.2) (4.2.1)
ERROR: Package 'add-trailing-comma' requires a different Python: 3.6.13 not in '>=3.7'
```

Instead of an unexpected syntax error. I'm just pointing this out - it is a fairly simple fix on my side (don't use an old version of Python which was lying around on my development project), so I wanted to make sure the situation was clear (and give people a chance to google the exception if they find it).

**Comment by asottile** [comment]
the `>=3.6` isn't for source installations -- it's for pypi

**Comment by pelson** [comment]
> the >=3.6 isn't for source installations -- it's for pypi

No, it is for ``pip`` (and other PEP-345 & PEP-566 compliant) installation tools to use, whether from source, sdist, or other binary distributions.

I notice that ``pre-commit`` (rightly) uses such a compliant tool to install the package from a git repo (as can be seen on the aforementioned exception):

```
An unexpected error has occurred: CalledProcessError: command: ('/home/pelson/.cache/pre-commit/repolko2zs1a/py_env-python3.6/bin/python', '-mpip', 'install', '.')
```

So my point stands - you would get a better error if ``setup.py`` were not only Python 3.7+ syntax (or at this point, even making the project PEP-517 based and removing the ``setup.py`` altogether).

This is such a trivial point it isn't really worth us discussing it any more. Whatever you choose to do is good enough for me :+1:

**Comment by asottile** [comment]
> This is such a trivial point it isn't really worth us discussing

**Pull request merged**
